### ISSUE TITLE
Registration Page #2

### ISSUE THREAD

**Issue by joatu** [joatuapp/joatu-app#13] opened 2014-09-30 19:26 UTC
Include text & mandatory checkbox:

"I have read and I accept JoatU's terms of use."

Have "terms of use" be a live link to open in a new tab to our terms of use.

**Comment by undergroundwebdesigns** [comment] 2014-10-28 01:13
Closing this as a duplicate of #14

**Closed as completed by undergroundwebdesigns** 2014-10-28 01:13 UTC
Labels: enhancement, help wanted
