### ISSUE TITLE
Sign up form verification

### ISSUE THREAD

**Issue by AlessandroMinali** [joatuapp/joatu-app#21] opened 2014-10-01 01:59 UTC
can move to step 2 without any form verification (error given after doing this is not helpful either)

**Comment by undergroundwebdesigns** [comment] 2014-10-13 21:40
Can you please provide more detail? Which fields failed to validate? What was the unhelpful error message? How can we reproduce this?

**Comment by undergroundwebdesigns** [comment] 2014-10-28 00:55
Closing as dead, cannot reproduce.

**Closed as completed by undergroundwebdesigns** 2014-10-28 00:55 UTC
Labels: bug
