### ISSUE TITLE
Trapped in info page, empty

### ISSUE THREAD

**Issue by CatherineBourgeois** [joatuapp/joatu-app#31] opened 2014-10-07 00:58 UTC
Mac OS X 10.9.4 2.5 GHz Intel Core i7 16 G. 1600 MHz DDR3
running Safari Version 7.0.6 (9537.78.2)
(see previous posts)
clicked question mark in menu
arrived in an empty page, no content, no menu, nothing clickable.
Trapped with refresh, no logo to click to go back to the home page.

**Comment by undergroundwebdesigns** [comment] 2014-10-13 22:01
Marking this a duplicate of #8, once we have a real about page, we'll also make the question mark icon link to it. If you want to fix this, please do #8 first, then update the question mark link :).

**Closed as completed** 2014-10-28 00:32 UTC
Labels: bug, help wanted
