### ISSUE TITLE
Home page / Login and Signup buttons not responding.

### ISSUE THREAD

**Issue by CatherineBourgeois** [joatuapp/joatu-app#20] opened 2014-10-01 01:48 UTC

**Comment by joatu** [comment] 2014-10-01 01:49
This needs a description (and a tag).  How can someone else replicate this issue?  What browser are you using?

**Comment by joatu** [comment] 2014-10-01 02:02
I can reproduce this error using Firefox 32.0.3.  Login & Signup buttons do nothing.

**Comment by undergroundwebdesigns** [comment] 2014-10-06 14:35
Possible duplicate of #24

**Closed as completed** 2014-10-06 15:56 UTC
Labels: bug
